Traceback (most recent call last):
  File "/home/robotics20/Documents/rotem/main.py", line 156, in <module>
    main(args_config, device)
  File "/home/robotics20/Documents/rotem/main.py", line 116, in main
    model, optimizer = Run_model.train_epoch(epoch=epoch, model=model, train_loader=train_loader
  File "/home/robotics20/Documents/rotem/Run_model.py", line 8, in train_epoch
    model.cuda()
  File "/home/robotics20/anaconda3/envs/rotem/lib/python3.10/site-packages/torch/nn/modules/module.py", line 749, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/robotics20/anaconda3/envs/rotem/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/home/robotics20/anaconda3/envs/rotem/lib/python3.10/site-packages/torch/nn/modules/module.py", line 664, in _apply
    param_applied = fn(param)
  File "/home/robotics20/anaconda3/envs/rotem/lib/python3.10/site-packages/torch/nn/modules/module.py", line 749, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/robotics20/anaconda3/envs/rotem/lib/python3.10/site-packages/torch/cuda/__init__.py", line 229, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available